version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  snyk-to-html:
    docker:
      - image: cimg/node:12.13.1
    steps:
      - checkout
      - run:
          name: snyk to html
          command: |            
            npm install snyk
            npm install snyk-to-html
            snyk test --json | snyk-to-html -o results.html
      - store_artifacts:
            path: /project/html
  snyk-test:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - snyk/scan:
          command: test
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: medium
workflows:
  test:
    jobs:
      - snyk-to-html
      - snyk-test