name: Snyk Container Scan
on: [push, pull_request]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t docker-goof .
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: docker-goof
        args: --file=Dockerfile
        
    - name: Snyk Import API
      run: | 
        curl --include \
        --request POST \
        --header "Content-Type: application/json; charset=utf-8" \
        --header "Authorization: ${API_TOKEN} " \
        --data-binary "{
        \"target\": {
        \"name\": \"shannreid/docker-goof:latest\"
          }
        }" \
        'https://api.snyk.io/api/v1/org/${ORG_ID}/integrations/${INTEGRATION_ID}/import'
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        INTEGRATION_ID: ${{ secrets.INTEGRATION_ID }}
        ORG_ID: ${{ secrets.ORG_ID }}
