name: Snyk Security Scan
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: install snyk
        run: npm install -g snyk
      - name: install snyk-to-html
        run: npm install -g snyk-to-html
      - name: run snyk test to html
        run: snyk test --json > results.json




