name: Snyk Security Scan
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: install snyk/snyk-to-html and run scan
        run: |
          sudo npm install snyk --location=global
          snyk auth ${{ secrets.SNYK_TOKEN }}
          npm install snyk-to-html --location=global
          snyk test --json | snyk-to-html -o results.html
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
      - name: Archive Snyk Code Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: Archive Snyk Code Scan Results
          path: results.html



