name: Snyk Infrastructure as Code Scan
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps: 
      - name: install AWS CDK cli
        run: npm install -g aws-cdk 
      - name: run build
        run: npm run build --if-present
      - name: convert cdk template to json
        run: cdk synth --json 
      - name: change directories to cdk.out
        run: cd cdk.out
      - name: Run IaC test for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
